# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

target 'Google-Stock-API' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Google-Stock-API
  pod 'Alamofire', '~> 4.0'
end
